<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.6 c:\Users\goran\Desktop\crep.gltf --transform --suspense --draco=/draco/
-->

<script>
// @ts-nocheck

	import { T } from '@threlte/core'
	import { useGltf, useSuspense, useDraco } from '@threlte/extras'
	import { MeshStandardMaterial } from 'three';

	let { fallback, error, children, ref = $bindable(), ...props } = $props()

	const suspend = useSuspense()

	const gltf = suspend(useGltf('/crep-transformed.glb', { dracoLoader: useDraco() }))
</script>

<T.Group
	bind:ref
	dispose={false}
	{...props}
>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			position={[1,3,1]}
			rotation.x={45}
			geometry={gltf.nodes.ORIGINALES_TEJA.geometry}
		>
			<T.MeshPhysicalMaterial side={2} color="silver" metalness={1} roughness={0.05} ></T.MeshPhysicalMaterial>
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
